name: Main workflow
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v1.1.0
      
      - name: Build lexer and parser
        uses: ./.github/actions/build-action     
